# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 7.1.3
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:30"
      timezone: "Asia/Shanghai"
    assignees:
      - "weishaodaren"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "10:30"
      timezone: "Asia/Shanghai"
    assignees:
      - "weishaodaren"
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"
